import pg from "pg";
import { config } from "./config.js";
const { Pool }=pg;
export const pool=new Pool({connectionString:config.DATABASE_URL,max:10});
export async function migrate():Promise<void>{
 await pool.query(`
CREATE TABLE IF NOT EXISTS users(id UUID PRIMARY KEY,github_id TEXT UNIQUE NOT NULL,github_login TEXT NOT NULL,github_name TEXT,github_avatar_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS github_accounts(user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,access_token_enc TEXT NOT NULL,refresh_token_enc TEXT,access_expires_at TIMESTAMPTZ,refresh_expires_at TIMESTAMPTZ,scopes TEXT NOT NULL DEFAULT '',updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions(expires_at);
CREATE TABLE IF NOT EXISTS mobile_auth_codes(code_hash TEXT PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ); CREATE INDEX IF NOT EXISTS mobile_auth_codes_expires_idx ON mobile_auth_codes(expires_at);
CREATE TABLE IF NOT EXISTS projects(id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',repo_owner TEXT,repo_name TEXT,branch TEXT NOT NULL DEFAULT 'main',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS projects_user_idx ON projects(user_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS chat_sessions(id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,project_id UUID REFERENCES projects(id) ON DELETE SET NULL,title TEXT NOT NULL,model_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS chat_sessions_user_idx ON chat_sessions(user_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS chat_messages(id BIGSERIAL PRIMARY KEY,session_id UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,role TEXT NOT NULL CHECK(role IN ('user','assistant','system')),content TEXT NOT NULL,model_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS chat_messages_session_idx ON chat_messages(session_id,created_at);
CREATE TABLE IF NOT EXISTS agent_runs(id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,status TEXT NOT NULL,model TEXT NOT NULL,tool_calls INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),finished_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS audit_log(id BIGSERIAL PRIMARY KEY,user_id UUID REFERENCES users(id) ON DELETE SET NULL,action TEXT NOT NULL,resource TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS termux_bridges(id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,token_hash TEXT UNIQUE NOT NULL,connected_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),last_seen_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS termux_commands(id UUID PRIMARY KEY,user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,bridge_id UUID REFERENCES termux_bridges(id) ON DELETE SET NULL,project_id TEXT NOT NULL,command TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL,destructive BOOLEAN NOT NULL DEFAULT false,exit_code INTEGER,stdout TEXT,stderr TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS termux_queue_idx ON termux_commands(user_id,status,created_at);
`);
}